### ISSUE TITLE
[Bug]: Both standalone and Win64 give OpenGL error on Windows 10 64-bit Intel CPU

### ISSUE THREAD

**Issue by fleeglespondo** [chrislo27/PolyrhythmMania#13]
### Version

v1.0.0

### Operating System

Windows 10

### Problem Description

On any version of Java, with both the platform-agnostic and Win64 versions, an error occurs when trying to start from LaunchPolyrhythmMania.exe or play_windows.bat, respectively. I expect this has something to do with the similar bug with RHRE3, but this time it's not mitigated by Java 8u25.

### Steps to Reproduce Problem

1. Get access to some version of 64-bit Windows 10, running on an Intel CPU.
2. Download and unzip either or both versions of the program.
3. Run either or both of the executables (play_windows.bat, launchpolyrhythmmania.exe).

### Relevant log output

```shell
For the standalone version:

[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:469)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
                paintbox.desktop.PaintboxDesktopLauncher$launch$app$1.<init>(PaintboxDesktopLauncher.kt:32)
                paintbox.desktop.PaintboxDesktopLauncher.launch(PaintboxDesktopLauncher.kt:32)
                polyrhythmmania.desktop.DesktopLauncher.main(DesktopLauncher.kt:65)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:472)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
        at paintbox.desktop.PaintboxDesktopLauncher$launch$app$1.<init>(PaintboxDesktopLauncher.kt:32)
        at paintbox.desktop.PaintboxDesktopLauncher.launch(PaintboxDesktopLauncher.kt:32)
        at polyrhythmmania.desktop.DesktopLauncher.main(DesktopLauncher.kt:65)
AL lib: (EE) alc_cleanup: 1 device not closed

For the Win64 version:

[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:469)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
                paintbox.desktop.PaintboxDesktopLauncher$launch$app$1.<init>(PaintboxDesktopLauncher.kt:32)
                paintbox.desktop.PaintboxDesktopLauncher.launch(PaintboxDesktopLauncher.kt:32)
                polyrhythmmania.desktop.DesktopLauncher.main(DesktopLauncher.kt:65)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:472)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
        at paintbox.desktop.PaintboxDesktopLauncher$launch$app$1.<init>(PaintboxDesktopLauncher.kt:32)
        at paintbox.desktop.PaintboxDesktopLauncher.launch(PaintboxDesktopLauncher.kt:32)
        at polyrhythmmania.desktop.DesktopLauncher.main(DesktopLauncher.kt:65)
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by chrislo27** [comment]
What Intel CPU are you running? The information is accessible through Task Manager: Open Task Manager, "More details", Performance tab, CPU, the name is on the right side.

You may want to try updating video card drivers per this Minecraft support article: https://help.minecraft.net/hc/en-us/articles/360029643912--Updating-video-card-drivers

You may also want to verify that your system specs meet *Minecraft: Java Edition's* minimum specs as they use the same underlying OpenGL library (GLFW): https://help.minecraft.net/hc/en-us/articles/360035131371-Minecraft-Java-Edition-system-requirements-

**Comment by fleeglespondo** [comment]
I'm running an Intel Core i5-2400 @ 3.10GHz; I think the graphics drivers are as up to date as they'll ever be on this system.
I can run Minecraft Java just fine. I have a pretty low-end computer, feel free to mark this as like, lowest priority.

**Comment by chrislo27** [comment]
Your CPU is below the minimum specifications: Intel Core i3-3210. Intel HD Graphics 4000 and newer are needed for OpenGL 4.4. Intel 3rd gen is over 10 years old now.

The problem is of hardware, not software. Minecraft Java Edition 1.17 also switched to OpenGL 4.4 and has raised the [minimum requirements](https://www.reddit.com/r/techsupport/comments/o13twi/i_cant_play_117_because_of_an_error/).
