### ISSUE TITLE
[Bug]: GLFW_VERSION_UNAVAILABLE error on Manjaro with NVIDIA drivers

### ISSUE THREAD

**Issue by RyutoSetsujin** [chrislo27/PolyrhythmMania#47]
### Version

v1.2.1-20220502a

### Operating System

Linux

### Problem Description

Game will not launch on my current hardware configuration, giving "GLFW_VERSION_UNAVAILABLE" errors.
```shell
Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060] driver: nvidia v: 510.60.02
  Device-2: Logitech StreamCam type: USB
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo
  Display: x11 server: X.Org v: 21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1: 1680x1050~60Hz 2: 1050x1680~60Hz 3: 1920x1080
  OpenGL: renderer: N/A v: N/A
```

### Steps to Reproduce Problem

1. Launch the game using openjdk 18, using the "java -java bin/polyrhythmmania.jar"

### Relevant log output

```shell
[LWJGL] GLFW_VERSION_UNAVAILABLE error
        Description : GLX: Failed to create context: BadValue (integer parameter out of range for operation)
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:469)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
                paintbox.desktop.PaintboxDesktopLauncher$launch$app$1.<init>(PaintboxDesktopLauncher.kt:40)
                paintbox.desktop.PaintboxDesktopLauncher.launch(PaintboxDesktopLauncher.kt:40)
                polyrhythmmania.desktop.DesktopLauncher.main(DesktopLauncher.kt:85)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:472)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
        at paintbox.desktop.PaintboxDesktopLauncher$launch$app$1.<init>(PaintboxDesktopLauncher.kt:40)
        at paintbox.desktop.PaintboxDesktopLauncher.launch(PaintboxDesktopLauncher.kt:40)
        at polyrhythmmania.desktop.DesktopLauncher.main(DesktopLauncher.kt:85)
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by RyutoSetsujin** [comment]
Was an issue with the NVIDIA driver configurations.
